<?php
/**
 * This class is used for autocomplete.
 * Class _AUTOLOAD_
 * @noautoload it avoids to index this class
 * @generated by AutoLoadOne 1.10 generated 2018/10/15 06:17:04
 * @copyright Copyright Jorge Castro C - MIT License. https://github.com/EFTEC/AutoLoadOne
 */
class _AUTOLOAD_
{
    var $debug=false;
    /* @var string[] Where $_arrautoloadCustom['namespace\Class']='folder\file.php' */
    private $_arrautoloadCustom = array(
		'ComposerAutoloaderInit3e1b6ae07f8144c067312ba0d9dd535e' => '/../vendor/composer/autoload_real.php',
		'Composer\Autoload\ComposerStaticInit3e1b6ae07f8144c067312ba0d9dd535e' => '/../vendor/composer/autoload_static.php',
		'eftec\DaoOne' => '/../vendor/eftec/daoone/lib/DaoOne.php',
		'eftec\SecurityOne' => '/../vendor/eftec/securityone/lib/SecurityOne.php',
		'eftec\MessageItem' => '/../vendor/eftec/validationone/lib/MessageItem.php',
		'eftec\MessageList' => '/../vendor/eftec/validationone/lib/MessageList.php',
		'eftec\ValidationItem' => '/../vendor/eftec/validationone/lib/ValidationItem.php',
		'eftec\ValidationOne' => '/../vendor/eftec/validationone/lib/ValidationOne.php'
    );
    /* @var string[] Where $_arrautoload['namespace']='folder' */
    private $_arrautoload = array(
		'eftec' => '/../lib',
		'Composer\Autoload' => '/../vendor/composer',
		'eftec\bladeone' => '/../vendor/eftec/bladeone/lib',
		'PHPMailer\PHPMailer' => '/../vendor/phpmailer/phpmailer/src'
    );
    /* @var boolean[] Where $_arrautoload['namespace' or 'namespace\Class']=true if it's absolute (it uses the full path) */
    private $_arrautoloadAbsolute= array(

    );    
    /**
     * _AUTOLOAD_ constructor.
     * @param bool $debug
     */
    public function __construct($debug=false)
    {
        $this->debug = $debug;
    }
    /**
     * @param $class_name
     * @throws Exception
     */
    public function auto($class_name) {
        // its called only if the class is not loaded.
        $ns = dirname($class_name); // without trailing
        $ns=($ns==".")?"":$ns;        
        $cls = basename($class_name);
        // special cases
        if (isset($this->_arrautoloadCustom[$class_name])) {
            $this->loadIfExists($this->_arrautoloadCustom[$class_name],$class_name);
            return;
        }
        // normal (folder) cases
        if (isset($this->_arrautoload[$ns])) {
            $this->loadIfExists($this->_arrautoload[$ns]."/".$cls.".php",$ns);
            return;
        }
    }

    /**
     * We load the file.    
     * @param string $filename
     * @param string $key key of the class it could be the full class name or only the namespace
     * @throws Exception
     */
    public function loadIfExists($filename,$key)
    {
        if (isset($this->_arrautoloadAbsolute[$key])) {
            $fullFile=$filename; // its an absolute path
        } else {
            $fullFile=__DIR__."/".$filename; // its relative to this path
        }
        if((@include $fullFile) === false) {
            if ($this->debug) {
                throw  new Exception("AutoLoadOne Error: Loading file [".__DIR__."/".$filename."] for class [".basename($filename)."]");
            } else {
                throw  new Exception("AutoLoadOne Error: No file found.");
            }
        }
    }
} // end of the class _AUTOLOAD_
if (defined('_AUTOLOAD_ONEDEBUG')) {
    $_AUTOLOAD_=new _AUTOLOAD_(_AUTOLOAD_ONEDEBUG);
} else {
    $_AUTOLOAD_=new _AUTOLOAD_(false);
}
spl_AUTOLOAD_register(function ($class_name)
{
    global $_AUTOLOAD_;
    $_AUTOLOAD_->auto($class_name);
});
// autorun

