<?php
/**
 * This class is used for autocomplete.
 * Class _AUTOLOAD_
 * @noautoload it avoids to index this class
 * @generated by AutoLoadOne 1.6 generated 2018/09/30 08:57:07
 * @copyright Copyright Jorge Castro C - MIT License. https://github.com/EFTEC/AutoLoadOne
 */
class _AUTOLOAD_
{
    var $debug=false;
    private $_arrautoloadCustom = array(
		'ComposerAutoloaderInit369923c50b0ca768b7ce500d852cb2ae' => '/../vendor/composer/autoload_real.php',
		'Composer\Autoload\ComposerStaticInit369923c50b0ca768b7ce500d852cb2ae' => '/../vendor/composer/autoload_static.php',
		'eftec\DaoOne' => '/../vendor/eftec/daoone/lib/DaoOne.php',
		'eftec\SecurityOne' => '/../vendor/eftec/securityone/lib/SecurityOne.php',
		'eftec\ErrorItem' => '/../vendor/eftec/validationone/lib/ErrorItem.php',
		'eftec\ErrorList' => '/../vendor/eftec/validationone/lib/ErrorList.php',
		'eftec\ValidationItem' => '/../vendor/eftec/validationone/lib/ValidationItem.php',
		'eftec\ValidationOne' => '/../vendor/eftec/validationone/lib/ValidationOne.php'
    );
    private $_arrautoload = array(
		'eftec' => '/../lib',
		'Composer\Autoload' => '/../vendor/composer',
		'eftec\bladeone' => '/../vendor/eftec/bladeone/lib',
		'mapache_commons' => '/../vendor/eftec/daoone/test',
		'PHPMailer\PHPMailer' => '/../vendor/phpmailer/phpmailer/src'
    );
    /**
     * _AUTOLOAD_ constructor.
     * @param bool $debug
     */
    public function __construct($debug=false)
    {
        $this->debug = $debug;
    }
    /**
     * @param $class_name
     * @throws Exception
     */
    public function auto($class_name) {
        // its called only if the class is not loaded.
        $ns = dirname($class_name); // without trailing
        $ns=($ns==".")?"":$ns;        
        $cls = basename($class_name);
        // special cases
        if (isset($this->_arrautoloadCustom[$class_name])) {
            $this->loadIfExists($this->_arrautoloadCustom[$class_name] );
            return;
        }
        // normal (folder) cases
        if (isset($this->_arrautoload[$ns])) {
            $this->loadIfExists($this->_arrautoload[$ns] . "/" . $cls . ".php");
            return;
        }
    }

    /**
     * @param $filename
     * @throws Exception
     */
    public function loadIfExists($filename)
    {
        if((@include __DIR__."/".$filename) === false) {
            if ($this->debug) {
                throw  new Exception("AutoLoadOne Error: Loading file [".__DIR__."/".$filename."] for class [".basename($filename)."]");
            } else {
                throw  new Exception("AutoLoadOne Error: No file found.");
            }
        }
    }
} // end of the class _AUTOLOAD_
if (defined('_AUTOLOAD_ONEDEBUG')) {
    $_AUTOLOAD_=new _AUTOLOAD_(_AUTOLOAD_ONEDEBUG);
} else {
    $_AUTOLOAD_=new _AUTOLOAD_(false);
}
spl_AUTOLOAD_register(function ($class_name)
{
    global $_AUTOLOAD_;
    $_AUTOLOAD_->auto($class_name);
});
// autorun

