
-- version  Generated by Table(20170604) 2018-09-27 17:48:27 
-- SET FOREIGN_KEY_CHECKS=0;
drop table IF EXISTS `sec_users`;
CREATE TABLE `sec_users`(	
	`iduser` INT NOT NULL AUTO_INCREMENT,
	`user` VARCHAR(50) NOT NULL DEFAULT '',
	`password` VARCHAR(64) NOT NULL DEFAULT '',
	`role` VARCHAR(50) NOT NULL DEFAULT '',
	`fullname` VARCHAR(50) NOT NULL DEFAULT '',
	`email` VARCHAR(50) NOT NULL DEFAULT '',
	`phone` VARCHAR(50) NOT NULL DEFAULT '',
	`address` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`iduser`)
);
-- alter
ALTER TABLE `sec_users` ADD COLUMN `iduser` int  NOT NULL DEFAULT 0;
ALTER TABLE `sec_users` ADD COLUMN `user` varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE `sec_users` ADD COLUMN `password` varchar(64)  NOT NULL DEFAULT '';
ALTER TABLE `sec_users` ADD COLUMN `role` varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE `sec_users` ADD COLUMN `fullname` varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE `sec_users` ADD COLUMN `email` varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE `sec_users` ADD COLUMN `phone` varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE `sec_users` ADD COLUMN `address` varchar(50)  NOT NULL DEFAULT '';
-- INDEXES:
-- todo : type#onetoone 
-- foreign keys
-- insert

insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
insert into sec_users(iduser,user,password,role,fullname,email,phone,address) values ('Text');
-- SET FOREIGN_KEY_CHECKS=1;
